Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2021-06, with the labels that each got.

#363 Update undead
  other/underworld/undead
Labels: clarification

#364 define "success" for attacks
  _rules/attacks/1 basics
Labels: clarification

#365 Additional attack edge case resolution
  _rules/attacks/3 block
  _rules/attacks/4 attack order
Labels: clarification, edge case

#383 Event Order Conflict Resolution
  _rules/events/2 order
Labels: clarification, edge case

#387 Rename Infected Wolf to Infecting Wolf
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Werewolf Power
  werewolves/power/infected wolf
  werewolves/power/infecting wolf
Labels: clarification

#386 Make WWW imitate most common WM
  other/solo/white werewolf
Labels: balancing

#392 Update wisp
  limited/wisp
Labels: balancing

#340 Hags - Unique UA Suggestion
  book
  categories/Solo Killing
  categories/Unaligned Align
  categories/Unaligned Align Hag
  unaligned/align - hag/bitter hag
  unaligned/align - hag/cautious hag
  unaligned/align - hag/hags
  unaligned/align - hag/prophetic hag
  unaligned/align - hag/vicious hag
Labels: new role, v13

#309 Create direwolf
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Werewolf
  categories/Werewolf Killing
  categories/Werewolf Power
  limited/direwolf
Labels: new role, v13

#330 Create amnesiac
  categories/Townsfolk Miscellaneous
  limited/amnesiac
Labels: new role, v13

#394 Create cat
  categories/Unaligned Align
  limited/cat
Labels: new role, v13

#268 Add Tasty Villager
  categories/Townsfolk Miscellaneous
  limited/fat guy
Labels: new role, v13

#331 Create Herald
  categories/Townsfolk Power
  limited/herald
Labels: new role, v13

#404 Make Guardian protect from NKs
  elected/guardian
Labels: balancing

#269 Update & Rebrand Evil Scientist
  categories/Solo Killing
  categories/Solo Miscellaneous
  categories/Solo Team Disease
  categories/Solo Team Plague
  categories/Unaligned Miscellaneous
  limited/evil scientist
  limited/exorcist
  limited/immune survivor
  limited/lab assistant
  limited/plague bearer
  limited/plague carrier
  limited/plague doctor
Labels: balancing, clarification, v13

#393 Update despot
  unaligned/miscellaneous/despot
Labels: balancing

#411 Create Uncertain Hag
  categories/Unaligned Align
  categories/Unaligned Align Hag
  unaligned/align - hag/Uncertain Hag
Labels: new role

#390 Update shepherd
  limited/exorcist
  limited/shepherd
Labels: feature, needs testing
