Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2021-04, with the labels that each got.

#47 attacked => killed
  other/underworld/vampire
Labels: bug

#51 Cult is disbanded
  townsfolk/group/cult member
  townsfolk/killing/cult leader
Labels: clarification

#45 Trickster Role Loss
  townsfolk/miscellaneous/trickster
Labels: clarification

#48 RH version from role book
  unaligned/miscellaneous/riding hood
Labels: bug

#46 Journalist Role Lose
  townsfolk/miscellaneous/journalist
Labels: clarification

#49 end night => end-night
  limited/evil scientist
  limited/ice queen
  limited/reaper
  other/pyro/pyromancer
  other/solo/white werewolf
  townsfolk/group/cult member
  townsfolk/killing/assassin
  townsfolk/killing/cult leader
  townsfolk/killing/priest
  townsfolk/killing/witch
  unaligned/miscellaneous/chef
  werewolves/power/lone wolf
Labels: bug

#15 Update medium
  townsfolk/power/medium
Labels: clarification

#70 Update mad scientist
  townsfolk/killing/mad scientist
Labels: clarification

#71 Update plaguebearer: tainting/demonising
  limited/plaguebearer
Labels: clarification

#68 Update wolfs cub
  werewolves/miscellaneous/wolfs cub
Labels: clarification

#82 Update flute player
  other/flute/flute player
Labels: clarification

#56 Devil cant be wager killed
  other/hell/devil
Labels: clarification

#77 Wolf cult members can vote
  townsfolk/group/cult member
  townsfolk/killing/cult leader
Labels: bug

#84 Update warlock
  werewolves/investigative/warlock
Labels: clarification

#58 Pack Tanner as Limited role
  limited/pack tanner
Labels: enhancement

#59 Lab Assistant as Limited Role
  limited/lab assistant
Labels: enhancement

#81 Create thief
  limited/thief
Labels: enhancement

#83 Oracle not affected by disguises
  townsfolk/investigative/oracle
Labels: bug

#14 Dog & Cursed Civilian
  limited/cursed civilian alt
  townsfolk/miscellaneous/cursed civilian
  unaligned/align/dog
Labels: clarification

#85 Solo category change (<Team> <Category> => Solo <Category> {- <Team> Team})
  limited/archangel
  limited/evil scientist
  limited/flute apprentice
  limited/ice queen
  limited/plaguebearer
  limited/reaper
  limited/saint
  limited/wisp
  limited/zombie
  other/flute/flute player
  other/hell/demon
  other/hell/devil
  other/ice royals/ice king
  other/pyro/pyromancer
  other/underworld/undead
  other/underworld/vampire
Labels: clarification

#17 Coroner Buff
  limited/coroner
Labels: enhancement

#63 Clairvoyant Fox draft
  limited/clairvoyant fox
Labels: enhancement, needs testing

#79 Update grandma
  townsfolk/power/grandma
Labels: clarification

#76 Update mayor
  elected/mayor
Labels: bug

#92 Update town crier
  townsfolk/miscellaneous/town crier
Labels: clarification, enhancement

#103 Update saboteur wolf
  werewolves/power/saboteur wolf
Labels: clarification

#123 Order rules
  _rules/abilities/1 basics
  _rules/abilities/2 immediate abilities
  _rules/abilities/3 delaying abilities
  _rules/attacks/1 basics
  _rules/attacks/2 groups
  _rules/disguises/1 basics
  _rules/disguises/2 strong and weak
  _rules/disguises/3 current disguises
  _rules/first day/1 basics
  _rules/obstructions/1 basics
  _rules/obstructions/2 current obstructions
  _rules/role loss/1 basics
  _rules/role loss/2 current role losses
  _rules/wolfpack and lycans/1 wolfpack
  _rules/wolfpack and lycans/2 lycans
Labels: bug, clarification

#132 Remove "first"
  _categories/first day
  _rules/first day/1 basics
  book
  townsfolk/group/cult member
  townsfolk/killing/cult leader
  unaligned/align/cupid
  unaligned/align/dog
  unaligned/align/look-alike
  werewolves/power/infected wolf
Labels: clarification

#89 Update current disguises
  _rules/disguises/1 basics
  _rules/disguises/3 current disguises
  townsfolk/investigative/aura teller
  townsfolk/miscellaneous/bard
  townsfolk/miscellaneous/ranger
Labels: clarification

#97 Create shepherd
  limited/herding dog
  limited/shepherd
Labels: feature

#159 CS's checks at same time
  townsfolk/investigative/crowd seeker
Labels: clarification

#128 Hellhound Betrayal
  werewolves/miscellaneous/hellhound
Labels: feature

#175 Update barber
  townsfolk/killing/barber
Labels: bug, edge case

#177 Update fletchers-customer
  channels/fletchers-customer
Labels: bug, clarification

#178 Update 1 wolfpack
  _rules/wolfpack and lycans/1 wolfpack
Labels: clarification, edge case

#180 Update riding hood
  unaligned/miscellaneous/riding hood
Labels: balancing

#172 Update clairvoyant fox
  limited/clairvoyant fox
Labels: balancing

#181 Update mad scientist
  townsfolk/killing/mad scientist
Labels: bug, clarification

#176 Update pyromancer
  other/pyro/pyromancer
Labels: clarification

#171 Update flute player
  other/flute/flute player
Labels: balancing

#108 Flute apprentice
  _categories/redirections
  _rules/disguises/1 basics
  _rules/redirections/1 basics
  _rules/redirections/2 details
  _rules/redirections/3 current redirections
  book
  other/flute/flute apprentice
Labels: feature, needs testing
