Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2022-12, with the labels that each got.

#857 Horsemen edits
  limited/horseman of famine
  limited/horseman of pestilence
  limited/horsemen
Labels: clarification

#861 New Role: Cult Acolyte
  categories/Custom Cult
  categories/Limited Roles
  categories/Townsfolk Group
  channels/command/multi/cult
  channels/info/cult
  limited/cult acolyte
  townsfolk/group/cult member
  townsfolk/killing/cult leader
Labels: new role

#854 Give the Recluse immunity to wolf kills
  limited/recluse
Labels: balancing

#882 Shepherd Rewrite
  limited/Flock Powers
  limited/Herding
  limited/herding dog
  limited/shepherd
Labels: clarification

#859 Update executioner
  townsfolk/killing/executioner
Labels: balancing

#889 AH Balancing
  limited/amulet holder
Labels: balancing

#891 Update reaper
  limited/reaper
Labels: balancing
