Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2022-06, with the labels that each got.

#616 Allow lynch conditional end-day effects
  _rules/abilities/3 delaying abilities
Labels: feature

#628 Unlimit herald
  categories/Townsfolk Power
  townsfolk/power/herald
Labels: new role

#622 Wager: Allow changing attack target
  other/hell/wager
Labels: feature

#592 Delete corrupt wolf
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Werewolf Power
  limited/corrupt wolf
Labels: removal

#635 Delete the two s0g0 alt Vampire/Devil teams
  archive/archangel
  archive/channels/grace
  archive/channels/heaven
  archive/plaguebearer old
  archive/saint
  archive/saintly cupid
  archive/zombie
  archive/zombified cupid
Labels: clarification

#591 Some changes to cat
  categories/Unaligned Align
  limited/cat
  unaligned/align/cat
  unaligned/align/dog
Labels: balancing, clarification

#593 Update Stalker Channel Message Phrasing
  channels/stalker
Labels: clarification

#619 Tell bat who they demonize
  limited/bat
Labels: feature, balancing

#620 Dont inform FP who's enchanted
  other/flute/flute player
Labels: clarification, edge case

#623 Tell PC how many people have the plague
  other/plague/plague carrier
Labels: feature

#636 Thief Clarifications
  limited/thief
Labels: clarification

#632 Remove pyronner
  archive/pyronner
  categories/Solo Killing
  categories/Solo Team Pyro
Labels: removal

#627 Spirit as Reaper Recruit role + Less reaper recruit
  categories/Solo Miscellaneous
  categories/Solo Team Nightmare
  categories/Unaligned Align Cupid
  limited/reaper abilities
  limited/spirit
  unaligned/align - cupid/cupid variants
  unaligned/align - cupid/spectral cupid
Labels: balancing, removal

#642 Remake of corrupt wolf
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Werewolf Power
  limited/corrupt wolf
Labels: new role

#638 Shepherd Changes
  limited/shepherd
Labels: balancing, clarification

#618 Clarify some Plague things
  other/plague/plague bearer
Labels: clarification

#474 Create golem
  categories/Unaligned Miscellaneous
  limited/golem
Labels: new role

#634 White wolves
  _categories/solo
  _categories/white wolves
  book
  categories/Solo Killing
  categories/Solo Team White Wolves
  limited/scared white werewolf
  other/white wolves/white werewolf
  unaligned/align/look-alike cases
Labels: clarification

#585 Create Tracking Wolf
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Werewolf Investigative
  limited/tracker wolf
Labels: new role

#668 LA & Reaper => Spirit
  unaligned/align/look-alike cases
Labels: balancing

#671 Remove Angel's -1 vote
  channels/command/extra/angel
  channels/command/ind/angel
  unaligned/miscellaneous/angel
Labels: balancing

#687 Bat sr
  categories/Solo Power
  categories/Solo Recruitment
  limited/bat
Labels: bug
