Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2022-10, with the labels that each got.

#751 Mayor Negative Vote
  elected/mayor
Labels: clarification

#743 PB Edge Case
  other/plague/plague bearer
Labels: edge case

#752 CW should be immune against redirections
  limited/corrupt wolf
Labels: bug

#777 Fix FPxCupid edge case
  other/flute/flute player
Labels: bug

#782 Update exorcist
  townsfolk/power/exorcist
Labels: clarification

#780 Make Reaper SK
  categories/Limited Roles
  categories/Solo Killing
  categories/Solo Power
  limited/reaper
Labels: balancing

#754 Slight FPA buff
  other/flute/flute apprentice
Labels: balancing

#786 Update bard
  townsfolk/miscellaneous/bard
Labels: clarification

#729 Update bard
  townsfolk/miscellaneous/bard
Labels: balancing

#801 Priest/LWo Clarification re No Attack on UA
  townsfolk/killing/priest
  werewolves/killing/lone wolf
Labels: clarification

#737 Role Suggestion: Alcoholic
  categories/Limited Roles
  categories/Townsfolk Miscellaneous
  limited/alcoholic
Labels: needs testing, new role

#802 Dog/Cat, replace TC option with Journalist
  unaligned/align/cat
  unaligned/align/dog
Labels: balancing

#798 Create firebug
  categories/Limited Roles
  categories/Solo Killing
  categories/Solo Team Pyro
  limited/firebug
Labels: needs testing, new role

#772 Horseman Solo Team
  categories/Limited Roles
  categories/Solo Killing
  categories/Solo Power
  categories/Solo Team Horsemen
  categories/Solo Teams
  categories/Unaligned Align Cupid
  channels/command/multi/horsemen
  limited/apocalyptic horseman
  limited/horseman
  limited/horseman of death
  limited/horseman of famine
  limited/horseman of pestilence
  limited/horseman of war
  limited/horsemen
  townsfolk/power/exorcist
  unaligned/align - cupid/apocalyptic cupid
  unaligned/align - cupid/cupid alignment
  unaligned/align - cupid/cupid variants
Labels: needs testing, new role

#755 Create Flute Charmer
  categories/Limited Roles
  categories/Solo Power
  categories/Solo Team Flute
  channels/command/multi/flute_team
  limited/Flute Charmer
  townsfolk/power/exorcist
Labels: balancing, needs testing, new role

#672 Create Amulet Holder
  categories/Limited Roles
  categories/Townsfolk Killing
  channels/command/extra/amulet-of-protection
  channels/info/amulet-of-protection
  limited/amulet holder
Labels: needs testing, new role

#529 Detective
  categories/Limited Roles
  categories/Unaligned Miscellaneous
  limited/detective
Labels: needs testing, new role

#781 Update saboteur wolf
  werewolves/power/saboteur wolf
Labels: feature
