Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2022-05, with the labels that each got.

#436 IW edge case list
  werewolves/power/infecting wolf
Labels: clarification, edge case

#458 Properly add wk category
  _categories/werewolves killing
  _categories/werewolves power
  book
Labels: bug

#459 Correct solo role categories
  _categories/ice royals
  _categories/nightmare
  book
  limited/reaper
  limited/reaper abilities
  limited/wraith
Labels: bug

#450 Angel cancels following lynch
  unaligned/miscellaneous/angel
Labels: balancing

#468 Www is a lycan and wolfpack member
  categories/Custom Lycans
  categories/Custom Wolfpack
Labels: bug

#472 Archiving
  archive/archangel
  archive/channels/grace
  archive/channels/heaven
  archive/claimspace
  archive/cursed civilian alt
  archive/ice king
  archive/ice queen
  archive/innkeeper old
  archive/packless wolf
  archive/plaguebearer old
  archive/saint
  archive/saintly cupid
  archive/survivor
  archive/tasty villager
  archive/zombie
  archive/zombified cupid
Labels: bug

#434 CH protect against any wronging
  unaligned/align - hag/cautious hag
Labels: feature, balancing

#463 Classify Alpha Wolf as Werewolf Killing role
  categories/Werewolf Killing
  categories/Werewolf Power
  werewolves/killing/alpha wolf
Labels: bug, clarification

#437 IW failure on hit packless werewolf
  werewolves/power/infecting wolf
Labels: balancing, edge case

#473 White Werewolf Buff
  other/solo/white werewolf
Labels: balancing

#456 Trickster Wolf
  _categories/werewolves transformation
  book
  categories/Werewolf
  categories/Werewolf Transformation
  werewolves/power/infecting wolf
  werewolves/transformation/trickster wolf
Labels: feature, balancing, new role

#466 Remove Gray Werewolf
  archive/gray werewolf
  categories/Solo Killing
  categories/Solo Teams
Labels: future version

#507 Clarify Wager phases
  other/hell/devil
  other/hell/wager
Labels: bug, clarification

#508 Make Herald ability multi-use
  limited/herald
Labels: bug, clarification

#509 Clarifiction for how Hooker & Protection works
  townsfolk/power/hooker
Labels: clarification

#500 Psycho disguise works differently from all others
  _rules/disguises/1 basics
  _rules/disguises/3 current disguises
Labels: bug, clarification, edge case

#501 Improved Mayor Phrasing
  elected/mayor
Labels: clarification

#481 Fix Hags
  unaligned/align - hag/bitter hag
  unaligned/align - hag/cautious hag
  unaligned/align - hag/hags
  unaligned/align - hag/prophetic hag
  unaligned/align - hag/vicious hag
Labels: bug, balancing

#497 Create plagued cupid
  _rules/role loss/2 current role losses
  categories/Unaligned Align Cupid
  limited/plagued cupid
  unaligned/align - cupid/cupid alignment
  unaligned/align - cupid/cupid variants
Labels: edge case, new role

#537 Make the Wisp thing more clear
  other/pyro/wisp
Labels: clarification

#534 Update fortune apprentice
  townsfolk/miscellaneous/fortune apprentice
Labels: feature, balancing

#533 Bring back Vampire
  categories/Solo
  categories/Solo Miscellaneous
  categories/Solo Power
  categories/Solo Recruitment
  categories/Solo Team Underworld
  categories/Solo Teams
  categories/Townsfolk Miscellaneous
  categories/Townsfolk Power
  limited/devout villager
  other/underworld/undead
  other/underworld/vampire
  townsfolk/power/exorcist
Labels: feature, new role

#515 Clarify Lynches
  _rules/ability types/14 lynching
Labels: clarification

#514 Shepherd Clarification
  limited/shepherd
Labels: clarification, edge case

#513 Bard Role Change Narration
  townsfolk/miscellaneous/bard
Labels: clarification, edge case

#488 Cupid x LA
  unaligned/align/look-alike cases
Labels: edge case

#480 Buff & Add Plague
  _categories/plague
  book
  categories/Solo Killing
  categories/Solo Miscellaneous
  categories/Solo Team Plague
  categories/Solo Teams
  categories/Unaligned Align Cupid
  categories/Unaligned Miscellaneous
  other/plague/plague bearer
  other/plague/plague carrier
  other/plague/plague doctor
  unaligned/align - cupid/plagued cupid
  unaligned/align/look-alike cases
Labels: bug, balancing

#531 Cupid and hags
  _rules/role loss/2 current role losses
  categories/Solo Miscellaneous
  categories/Solo Team Hag
  categories/Solo Teams
  categories/Unaligned
  categories/Unaligned Align
  categories/Unaligned Align Hag
  unaligned/align - cupid/cupid alignment
  unaligned/align - cupid/cupid hag
  unaligned/align - cupid/cupid variants
  unaligned/align - hag/hags
Labels: edge case, new role

#548 Hell/Graveyard role loss case
  limited/zombie
Labels: edge case

#544 Shepherd & Exorcist
  townsfolk/power/exorcist
Labels: bug

#553 Exorcist Day Ability
  townsfolk/power/exorcist
Labels: feature

#563 Reaper Recruitment
  limited/reaper abilities
Labels: feature

#566 Create unemployed chef
  categories/Unaligned Miscellaneous
  limited/unemployed chef
Labels: new role

#567 Players can technically killed by several roles
  _rules/attacks/4 attack order
Labels: bug, clarification

#570 Update flute player
  other/flute/flute player
Labels: bug, clarification

#571 Shepherd Reaper Edge Case
  limited/reaper abilities
Labels: edge case

#574 Herding Dog Buff
  limited/herding dog
Labels: balancing

#573 Update corpse
  limited/corpse
Labels: new role

#555 wisp change
  other/pyro/wisp
Labels: balancing

#575 Scared WWW
  categories/Custom Lycans
  categories/Custom Wolfpack
  categories/Solo Killing
  categories/Solo Teams
  limited/scared white werewolf
Labels: new role

#554 Change weird Wisp behaivor
  other/pyro/wisp
Labels: feature

#584 Change Herding Dog
  categories/Solo Miscellaneous
  categories/Solo Power
  limited/herding dog
Labels: balancing

#583 WWW Clarification
  other/solo/white werewolf
Labels: clarification

#580 Make Shepherd betrayable
  channels/flock
Labels: bug

#578 Update white werewolf
  other/solo/white werewolf
Labels: bug

#572 General Reaper Solo Clarification
  limited/reaper abilities
Labels: clarification

#568 Wraith Attack consistent with Reaper
  categories/Solo Killing
  categories/Solo Miscellaneous
  limited/wraith
Labels: bug

#596 Update wraith
  limited/wraith
Labels: balancing

#590 Scared Wolf: Remove mention of Runner
  werewolves/miscellaneous/scared wolf
Labels: clarification, future version

#589 Improve Undead Phrasing
  limited/zombie
  other/underworld/undead
Labels: clarification

#598 Update thief
  limited/thief
Labels: bug
