Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2023-05, with the labels that each got.

#1061 Alphabetize
  categories/Custom Cult
  categories/Custom Foxes
  categories/Custom Lone Werewolves
  categories/Custom Packless Werewolves
  categories/Custom Wolfish
  categories/Solo Killing
  categories/Solo Miscellaneous
  categories/Solo Power
  categories/Solo Team Horsemen
  categories/Solo Team Nightmare
  categories/Townsfolk Power
  categories/Unaligned Hag
  categories/Werewolf Investigative
  categories/Werewolf Miscellaneous
Labels: bug

#1058 Add Test Subject as EM Role
  categories/Extra Miscellaneous
  extra/miscellaneous/test subject
  townsfolk/killing/mad scientist
Labels: clarification

#1057 Visits
  _rules/abilities/4 visits
Labels: clarification

#979 Update rogue wolf
  limited/rogue wolf
Labels: new role

#908 Create Coyotes
  categories/Custom Coyotes
  categories/Custom Lycanless
  categories/Custom Packless Werewolves
  categories/Custom Wolfish
  categories/Limited Roles
  categories/Werewolf Group
  categories/Werewolf Killing
  limited/greater coyote
  limited/lesser coyote
Labels: new role
