Repository WerewolvesRevamped/Werewolves-Roles, pull requests merged in 2024-09, with the labels that each got.

#1391 Remove Compound; Add AttrSelf
  Formalization Guide.md
  _game/attributes/contaminated
  _game/attributes/doomed
  _game/attributes/marker
  _game/teams/Hell
  _rules/roles/5 action
  limited/apothecary
  limited/baroness
  limited/detective
  limited/firebug
  limited/gallant fox
  limited/ravenkeeper
  limited/rival
  other/hell/devil
  other/pyro/pyromancer
  townsfolk/investigative/oracle
  townsfolk/killing/witch
  townsfolk/miscellaneous/macho
  townsfolk/power/exorcist
  townsfolk/power/herald
  townsfolk/power/royal knight
  unaligned/align - hag/vicious hag
  unaligned/investigative/psychopath
  unaligned/killing/chef
  werewolves/investigative/archivist fox
  werewolves/investigative/clairvoyant fox
  werewolves/power/disguised fox
Labels: feature, removal, code

#1388 Fixing typos
  other/flute/flute player
  unaligned/killing/chef
Labels: spag

#1392 Role Suggestion: Grave Robber
  _game/attributes/graverobberoption
  limited/grave robber
Labels: new role
